<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ST 558 HW 4 - Ben’s version</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-45431c2918bd31147ddb3fa7038bb99f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ST 558 HW 4 - Ben’s version</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Your API key is: 0009f78a3db94bc0b36a3a84d1cef3a7</p>
<section id="bens-work-goes-here" class="level2">
<h2 class="anchored" data-anchor-id="bens-work-goes-here">Ben’s work goes here</h2>
</section>
<section id="task-1---querying-an-api-and-a-tidy-style-function" class="level1">
<h1>Task 1 - Querying an API and a Tidy-Style Function</h1>
<p>Return information on recent Apple news</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>API_data <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="st">"https://newsapi.org/v2/everything?q=apple&amp;from=2026-06-10&amp;to=2026-06-10&amp;sortBy=popularity&amp;apiKey=0009f78a3db94bc0b36a3a84d1cef3a7"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(API_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 10
 $ url        : chr "https://newsapi.org/v2/everything?q=apple&amp;from=2026-06-10&amp;to=2026-06-10&amp;sortBy=popularity&amp;apiKey=0009f78a3db94b"| __truncated__
 $ status_code: int 200
 $ headers    :List of 14
  ..$ date             : chr "Fri, 12 Jun 2026 15:08:44 GMT"
  ..$ content-type     : chr "application/json; charset=utf-8"
  ..$ cache-control    : chr "no-cache"
  ..$ pragma           : chr "no-cache"
  ..$ expires          : chr "-1"
  ..$ x-cached-result  : chr "true"
  ..$ x-cache-remaining: chr "99"
  ..$ x-cache-expires  : chr "Fri, 12 Jun 2026 15:12:49 GMT"
  ..$ cf-cache-status  : chr "DYNAMIC"
  ..$ nel              : chr "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
  ..$ report-to        : chr "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=IZ2"| __truncated__
  ..$ content-encoding : chr "gzip"
  ..$ server           : chr "cloudflare"
  ..$ cf-ray           : chr "a0a9c5c9cad20580-IAD"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 $ all_headers:List of 1
  ..$ :List of 3
  .. ..$ status : int 200
  .. ..$ version: chr "HTTP/2"
  .. ..$ headers:List of 14
  .. .. ..$ date             : chr "Fri, 12 Jun 2026 15:08:44 GMT"
  .. .. ..$ content-type     : chr "application/json; charset=utf-8"
  .. .. ..$ cache-control    : chr "no-cache"
  .. .. ..$ pragma           : chr "no-cache"
  .. .. ..$ expires          : chr "-1"
  .. .. ..$ x-cached-result  : chr "true"
  .. .. ..$ x-cache-remaining: chr "99"
  .. .. ..$ x-cache-expires  : chr "Fri, 12 Jun 2026 15:12:49 GMT"
  .. .. ..$ cf-cache-status  : chr "DYNAMIC"
  .. .. ..$ nel              : chr "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}"
  .. .. ..$ report-to        : chr "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=IZ2"| __truncated__
  .. .. ..$ content-encoding : chr "gzip"
  .. .. ..$ server           : chr "cloudflare"
  .. .. ..$ cf-ray           : chr "a0a9c5c9cad20580-IAD"
  .. .. ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 $ cookies    :'data.frame':    0 obs. of  7 variables:
  ..$ domain    : logi(0) 
  ..$ flag      : logi(0) 
  ..$ path      : logi(0) 
  ..$ secure    : logi(0) 
  ..$ expiration: 'POSIXct' num(0) 
  ..$ name      : logi(0) 
  ..$ value     : logi(0) 
 $ content    : raw [1:88809] 7b 22 73 74 ...
 $ date       : POSIXct[1:1], format: "2026-06-12 15:08:44"
 $ times      : Named num [1:6] 0 0.003 0.0311 0.0763 0.144 ...
  ..- attr(*, "names")= chr [1:6] "redirect" "namelookup" "connect" "pretransfer" ...
 $ request    :List of 7
  ..$ method    : chr "GET"
  ..$ url       : chr "https://newsapi.org/v2/everything?q=apple&amp;from=2026-06-10&amp;to=2026-06-10&amp;sortBy=popularity&amp;apiKey=0009f78a3db94b"| __truncated__
  ..$ headers   : Named chr "application/json, text/xml, application/xml, */*"
  .. ..- attr(*, "names")= chr "Accept"
  ..$ fields    : NULL
  ..$ options   :List of 2
  .. ..$ useragent: chr "libcurl/8.14.1 r-curl/7.1.0 httr/1.4.8"
  .. ..$ httpget  : logi TRUE
  ..$ auth_token: NULL
  ..$ output    : list()
  .. ..- attr(*, "class")= chr [1:2] "write_memory" "write_function"
  ..- attr(*, "class")= chr "request"
 $ handle     :Class 'curl_handle' &lt;pointer: 0xa96e78300&gt; 
 - attr(*, "class")= chr "response"</code></pre>
</div>
</div>
<p>Find the article information</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'jsonlite'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    flatten</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># parse the url to find the content section</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(API_data<span class="sc">$</span>content))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(parsed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "status"       "totalResults" "articles"    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#make it a tibble</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>articles <span class="ot">&lt;-</span> parsed<span class="sc">$</span>articles <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">as_tibble</span>()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>articles</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 99 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 the-verge The … Jenni… Appl… Apple and … http… https://p… 2026-06-10… "&lt;ul&gt;&lt;…
 2 the-verge The … Sheen… The … Apple’s up… http… https://p… 2026-06-10… "&lt;ul&gt;&lt;…
 3 the-verge The … Terre… Deez… Deezer wil… http… https://p… 2026-06-10… "&lt;ul&gt;&lt;…
 4 the-verge The … Jay P… Appl… Apple's ne… http… https://p… 2026-06-10… "&lt;ul&gt;&lt;…
 5 the-verge The … Andre… Boox… Following … http… https://p… 2026-06-10… "&lt;ul&gt;&lt;…
 6 &lt;NA&gt;      Gizm… Kyle … The … The macOS … http… https://g… 2026-06-10… "If yo…
 7 &lt;NA&gt;      Gizm… Chery… Doom… The island… http… https://g… 2026-06-10… "Were …
 8 &lt;NA&gt;      Gizm… Germa… ‘Pro… Ryan Gosli… http… https://g… 2026-06-10… "A mon…
 9 &lt;NA&gt;      Andr… brady… Why … You don't … http… https://c… 2026-06-10… "I hav…
10 &lt;NA&gt;      Andr… chris… Sams… The Samsun… http… https://c… 2026-06-10… "If yo…
# ℹ 89 more rows</code></pre>
</div>
</div>
<p>Build a function to do this for us</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>news_search <span class="ot">&lt;-</span> <span class="cf">function</span>(search, start_date, api_key) {</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># get url</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  response <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="at">url =</span> <span class="st">"https://newsapi.org/v2/everything"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">query =</span> <span class="fu">list</span>(<span class="at">q =</span> search,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                               <span class="at">from =</span> start_date,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                               <span class="at">language =</span> <span class="st">"en"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                               <span class="at">pageSize =</span> <span class="dv">50</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">apiKey =</span> api_key))</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># find article information</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(response<span class="sc">$</span>content))</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make it a tibble</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  articles <span class="ot">&lt;-</span> parsed<span class="sc">$</span>articles <span class="sc">|&gt;</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as_tibble</span>()</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(articles)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s test our function</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Given example</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">news_search</span>(<span class="st">"Iran"</span>, <span class="dv">2026-05-02</span>, <span class="st">"0009f78a3db94bc0b36a3a84d1cef3a7"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 49 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 &lt;NA&gt;      BBC … &lt;NA&gt;   Iran… "Iran laun… http… https://i… 2026-06-08… "At le…
 2 wired     Wired Katie… The … "Jason Rez… http… https://m… 2026-05-26… "What …
 3 &lt;NA&gt;      BBC … &lt;NA&gt;   Gree… "The Metro… http… https://i… 2026-05-29… "\"We …
 4 &lt;NA&gt;      BBC … &lt;NA&gt;   Bowe… "Under pre… http… https://i… 2026-06-01… "It ha…
 5 &lt;NA&gt;      BBC … &lt;NA&gt;   Sail… "The uncer… http… https://i… 2026-06-02… "Among…
 6 &lt;NA&gt;      BBC … &lt;NA&gt;   Iran… "Iran said… http… https://i… 2026-06-08… "Iran …
 7 &lt;NA&gt;      BBC … &lt;NA&gt;   US l… "US Centra… http… https://i… 2026-06-10… "The i…
 8 &lt;NA&gt;      BBC … &lt;NA&gt;   Trum… "The reque… http… https://i… 2026-05-31… "The l…
 9 &lt;NA&gt;      BBC … &lt;NA&gt;   Iran… "Earlier I… http… https://i… 2026-06-01… "The I…
10 &lt;NA&gt;      BBC … &lt;NA&gt;   Son … "Craig and… http… https://i… 2026-06-07… "On hi…
# ℹ 39 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Top business headlines</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">news_search</span>(<span class="st">"business"</span>, <span class="dv">2026-06-11</span>, <span class="st">"0009f78a3db94bc0b36a3a84d1cef3a7"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 37 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 the-verge The … Tom W… Xbox… "The RAMag… http… https://p… 2026-06-10… "&lt;ul&gt;&lt;…
 2 wired     Wired Jorda… What… "Discover … http… https://m… 2026-05-21… "Photo…
 3 &lt;NA&gt;      BBC … &lt;NA&gt;   Faci… "In conver… http… https://i… 2026-06-11… "In so…
 4 &lt;NA&gt;      Gizm… Bruce… Andr… "The forme… http… https://g… 2026-06-02… "So, w…
 5 the-verge The … Andre… Phil… "Its name … http… https://p… 2026-05-21… "&lt;ul&gt;&lt;…
 6 the-verge The … Tom W… Micr… "Yusuf Meh… http… https://p… 2026-05-22… "&lt;ul&gt;&lt;…
 7 the-verge The … Andre… Volv… "Volvo onc… http… https://p… 2026-05-20… "&lt;ul&gt;&lt;…
 8 the-verge The … Stevi… Hond… "Honda rev… http… https://p… 2026-05-14… "&lt;ul&gt;&lt;…
 9 the-verge The … Janko… Is A… "This is L… http… https://p… 2026-06-11… "&lt;ul&gt;&lt;…
10 business… Busi… Alexa… My f… "My dad in… http… https://i… 2026-06-06… "The a…
# ℹ 27 more rows</code></pre>
</div>
</div>
<p>Works as expected</p>
</section>
<section id="task-2---summarizing-roller-coaster-data" class="level1">
<h1>Task 2 - Summarizing Roller Coaster Data</h1>
<p>Lets read in our data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>rcs_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://www4.stat.ncsu.edu/online/datasets/635USrollercoasters.csv"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># remove some columns</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>rcs <span class="ot">&lt;-</span> rcs_raw <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Boundary, Latitude, Longitude))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># look at types</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rcs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   635 obs. of  18 variables:
 $ Coaster         : chr  "Adrenaline Peak" "Adventure Express" "Afterburn" "Aftershock" ...
 $ Park            : chr  "Oaks Amusement Park" "Kings Island" "Carowinds" "Silverwood Theme Park" ...
 $ City            : chr  "Portland" "Mason" "Charlotte" "Athol" ...
 $ State           : chr  "Oregon" "Ohio" "North Carolina" "Idaho" ...
 $ Census.Region   : chr  "West" "Midwest" "South" "West" ...
 $ Year.Opened     : int  2018 1991 1999 2008 2010 1997 1998 1981 2008 1991 ...
 $ AgeGroup        : chr  "3:Newest" "2:Recent" "2:Recent" "3:Newest" ...
 $ TopSpeed        : num  45 35 62 65.6 22 67 35 66 48 50 ...
 $ MaxHeight       : num  72 63 113 192 25 ...
 $ Scale           : chr  "Extreme" "Thrill" "Extreme" "Extreme" ...
 $ Type            : chr  "Steel" "Steel" "Steel" "Steel" ...
 $ Design          : chr  "Sit Down" "Sit Down" "Inverted" "Inverted" ...
 $ Drop            : num  70 47 110 177 22.5 170 20 147 80 144 ...
 $ Length          : num  1050 2963 2956 1204 628 ...
 $ Duration        : int  66 140 167 92 47 190 100 143 110 110 ...
 $ Inversions.     : chr  "Yes" "No" "Yes" "Yes" ...
 $ X..of.Inversions: int  3 0 6 3 0 6 0 0 0 4 ...
 $ Make            : chr  "Gerstlauer Amusement Rides GmbH" "Arrow Dynamics" "Bolliger &amp; Mabillard" "Vekoma" ...</code></pre>
</div>
</div>
<p>Lets clean our data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>rcs <span class="ot">&lt;-</span> rcs_raw <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Boundary, Latitude, Longitude)) <span class="sc">|&gt;</span> <span class="co">#remove some columns</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">rename</span>(<span class="at">Inversions =</span><span class="st">`</span><span class="at">Inversions.</span><span class="st">`</span>, <span class="co">#rename some columns</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">Inversions.Count =</span> <span class="st">`</span><span class="at">X..of.Inversions</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(Census.Region, AgeGroup, Scale, Type, Design, Inversions), </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                          <span class="sc">~</span> <span class="fu">as.factor</span>(.))) <span class="sc">|&gt;</span> <span class="co">#turn some variables into factors</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">as_tibble</span>()</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rcs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [635 × 18] (S3: tbl_df/tbl/data.frame)
 $ Coaster         : chr [1:635] "Adrenaline Peak" "Adventure Express" "Afterburn" "Aftershock" ...
 $ Park            : chr [1:635] "Oaks Amusement Park" "Kings Island" "Carowinds" "Silverwood Theme Park" ...
 $ City            : chr [1:635] "Portland" "Mason" "Charlotte" "Athol" ...
 $ State           : chr [1:635] "Oregon" "Ohio" "North Carolina" "Idaho" ...
 $ Census.Region   : Factor w/ 4 levels "Midwest","Northeast",..: 4 1 3 4 3 3 2 1 1 3 ...
 $ Year.Opened     : int [1:635] 2018 1991 1999 2008 2010 1997 1998 1981 2008 1991 ...
 $ AgeGroup        : Factor w/ 3 levels "1:Older","2:Recent",..: 3 2 2 3 3 2 2 2 3 2 ...
 $ TopSpeed        : num [1:635] 45 35 62 65.6 22 67 35 66 48 50 ...
 $ MaxHeight       : num [1:635] 72 63 113 192 25 ...
 $ Scale           : Factor w/ 4 levels "Extreme","Family",..: 1 4 1 1 2 1 4 1 4 1 ...
 $ Type            : Factor w/ 2 levels "Steel","Wood": 1 1 1 1 1 1 1 2 2 1 ...
 $ Design          : Factor w/ 7 levels "Bobsled","Flying",..: 4 4 3 3 4 3 1 4 4 4 ...
 $ Drop            : num [1:635] 70 47 110 177 22.5 170 20 147 80 144 ...
 $ Length          : num [1:635] 1050 2963 2956 1204 628 ...
 $ Duration        : int [1:635] 66 140 167 92 47 190 100 143 110 110 ...
 $ Inversions      : Factor w/ 2 levels "No","Yes": 2 1 2 2 1 2 1 1 1 2 ...
 $ Inversions.Count: int [1:635] 3 0 6 3 0 6 0 0 0 4 ...
 $ Make            : chr [1:635] "Gerstlauer Amusement Rides GmbH" "Arrow Dynamics" "Bolliger &amp; Mabillard" "Vekoma" ...</code></pre>
</div>
</div>
<section id="basic-eda" class="level2">
<h2 class="anchored" data-anchor-id="basic-eda">Basic EDA</h2>
<p>Lets check the <code>summary</code> of the data to make sure everything looks okay</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rcs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Coaster           Park            City           State    
 Length   :635   Length   :635   Length   :635   Length   :635  
 N.unique :482   N.unique :197   N.unique :171   N.unique : 40  
 N.blank  :  0   N.blank  :  0   N.blank  :  0   N.blank  :  0  
 Min.nchar:  2   Min.nchar:  6   Min.nchar:  3   Min.nchar:  4  
 Max.nchar: 46   Max.nchar: 47   Max.nchar: 20   Max.nchar: 14  
                                                                
                                                                
   Census.Region  Year.Opened       AgeGroup      TopSpeed        MaxHeight    
 Midwest  :134   Min.   :1920   1:Older : 69   Min.   :  6.00   Min.   :  5.0  
 Northeast:156   1st Qu.:1995   2:Recent:190   1st Qu.: 28.50   1st Qu.: 28.0  
 South    :223   Median :2002   3:Newest:376   Median : 45.00   Median : 64.3  
 West     :122   Mean   :1999                  Mean   : 42.24   Mean   : 76.8  
                 3rd Qu.:2013                  3rd Qu.: 55.00   3rd Qu.:109.0  
                 Max.   :2020                  Max.   :128.00   Max.   :456.0  
                                               NAs    :74       NAs    :8      
     Scale        Type           Design         Drop            Length    
 Extreme:269   Steel:530   Bobsled  :  4   Min.   :  0.00   Min.   :  48  
 Family :178   Wood :105   Flying   :  9   1st Qu.: 25.00   1st Qu.: 900  
 Kiddie : 28               Inverted : 42   Median : 70.00   Median :1490  
 Thrill :160               Sit Down :560   Mean   : 77.18   Mean   :1938  
                           Stand Up :  4   3rd Qu.:108.50   3rd Qu.:2800  
                           Suspended:  7   Max.   :418.00   Max.   :7359  
                           Wing     :  9   NAs    :128      NAs    :33    
    Duration   Inversions Inversions.Count        Make    
 Min.   : 20   No :465    Min.   :0.0000   Length   :635  
 1st Qu.: 70   Yes:170    1st Qu.:0.0000   N.unique : 54  
 Median :101              Median :0.0000   N.blank  : 36  
 Mean   :106              Mean   :0.9213   Min.nchar:  0  
 3rd Qu.:130              3rd Qu.:1.0000   Max.nchar: 36  
 Max.   :540              Max.   :8.0000                  
 NAs    :66                                               </code></pre>
</div>
</div>
<p>Seems like everything checks out. Lets check the counts of missing values in the data by column</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(rcs))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Coaster             Park             City            State 
               0                0                0                0 
   Census.Region      Year.Opened         AgeGroup         TopSpeed 
               0                0                0               74 
       MaxHeight            Scale             Type           Design 
               8                0                0                0 
            Drop           Length         Duration       Inversions 
             128               33               66                0 
Inversions.Count             Make 
               0                0 </code></pre>
</div>
</div>
<p><code>Drop</code>, <code>TopSeed</code>, and <code>Duration</code> are the variables with the most missing values. They’re missing 128, 74, and 66 values respectively.</p>
</section>
<section id="categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="categorical-variables">Categorical Variables</h2>
<p>Lets create some contingency tables using <code>table()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#one-way table</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(rcs<span class="sc">$</span>Scale, <span class="at">useNA =</span> <span class="st">'always'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Extreme  Family  Kiddie  Thrill    &lt;NA&gt; 
    269     178      28     160       0 </code></pre>
</div>
</div>
<p>From the table we can see there are 269 extreme roller coasters in the dataset</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#two-way table</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(rcs<span class="sc">$</span>Scale, rcs<span class="sc">$</span>Census.Region, <span class="at">useNA =</span> <span class="st">'always'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          Midwest Northeast South West &lt;NA&gt;
  Extreme      61        62    92   54    0
  Family       32        49    68   29    0
  Kiddie        8         7     6    7    0
  Thrill       33        38    57   32    0
  &lt;NA&gt;          0         0     0    0    0</code></pre>
</div>
</div>
<p>From the table we can see there are 49 extreme roller coasters in the Midwest</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#three-way table</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(rcs<span class="sc">$</span>Scale, rcs<span class="sc">$</span>Census.Region, rcs<span class="sc">$</span>AgeGroup, <span class="at">useNA =</span> <span class="st">'always'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = 1:Older

         
          Midwest Northeast South West &lt;NA&gt;
  Extreme       6         3     5    3    0
  Family        2         7     4    0    0
  Kiddie        1         3     0    1    0
  Thrill        8         8     8   10    0
  &lt;NA&gt;          0         0     0    0    0

, ,  = 2:Recent

         
          Midwest Northeast South West &lt;NA&gt;
  Extreme      21        22    38   24    0
  Family        9        13     9    9    0
  Kiddie        3         3     0    3    0
  Thrill       12        10    10    4    0
  &lt;NA&gt;          0         0     0    0    0

, ,  = 3:Newest

         
          Midwest Northeast South West &lt;NA&gt;
  Extreme      34        37    49   27    0
  Family       21        29    55   20    0
  Kiddie        4         1     6    3    0
  Thrill       13        20    39   18    0
  &lt;NA&gt;          0         0     0    0    0

, ,  = NA

         
          Midwest Northeast South West &lt;NA&gt;
  Extreme       0         0     0    0    0
  Family        0         0     0    0    0
  Kiddie        0         0     0    0    0
  Thrill        0         0     0    0    0
  &lt;NA&gt;          0         0     0    0    0</code></pre>
</div>
</div>
<p>From the table we can see there are 7 extreme roller coasters in the Midwest that are considered to be ‘older’</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>